import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher; 
import java.util.regex.Pattern;



/**
 * Date: Jun 5, 2016 
 * Author: calumpatrick 
 * Program: 
 * Purpose:
 */

public class TextPatternsUI extends javax.swing.JFrame {

    /**
     * Creates new form TextPatternsUI
     */
    public TextPatternsUI() {
        initComponents();
    }
/**
 * Grabs the user's clipboard contents 
 */
     
    public static String getClip() throws Exception {

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Clipboard clipboard = toolkit.getSystemClipboard();
        String result = (String) clipboard.getData(DataFlavor.stringFlavor);
        return result;
    }
    
    public void compileReg() {
        S = sourceTextArea.getText();
        while (M.find()) {
        System.out.println(M.group());
        outputTextArea.append(M.group()+"\n");
        }
    }

    
    
/**
 * Find what the user wants to search for, and which RegEx to compile.
 * 
 * Mode 0 = Email
 * Mode 1 = Phone Numbers
 * Mode 2 = Website URLs
 * 
 */
    public int getMode() {
        int mode;
        if (modeEmailsRadio.isSelected()) {
            mode = 0;
            System.out.println("Searching for emails...");
        } else if (modePhoneRadio.isSelected()) {
            mode = 1;
            System.out.println("Searching for phone numbers...");
        } else {
            mode = 2;
            System.out.println("Searching for website URLs...");
        }
        
        return mode;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel4 = new javax.swing.JPanel();
        modeOptionsGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modeEmailsRadio = new javax.swing.JRadioButton();
        modePhoneRadio = new javax.swing.JRadioButton();
        modeWebsiteRadio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sourceClipboardButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sourceTextArea = new javax.swing.JTextArea();
        sourceGoButton = new javax.swing.JButton();
        sourceClearButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        outputResultsLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");

        jLabel1.setText("What would you like to search for?");

        modeOptionsGroup.add(modeEmailsRadio);
        modeEmailsRadio.setText("Emails");
        modeEmailsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeEmailsRadioActionPerformed(evt);
            }
        });

        modeOptionsGroup.add(modePhoneRadio);
        modePhoneRadio.setText("Phone Numbers");
        modePhoneRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modePhoneRadioActionPerformed(evt);
            }
        });

        modeOptionsGroup.add(modeWebsiteRadio);
        modeWebsiteRadio.setText("Website URLs");
        modeWebsiteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeWebsiteRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modeWebsiteRadio)
                    .addComponent(modePhoneRadio)
                    .addComponent(modeEmailsRadio)
                    .addComponent(jLabel1))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(modeEmailsRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modePhoneRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modeWebsiteRadio)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mode", jPanel1);

        jLabel3.setText("Text input:");

        sourceClipboardButton.setText("Copy from clipboard");
        sourceClipboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceClipboardButtonActionPerformed(evt);
            }
        });

        sourceTextArea.setColumns(20);
        sourceTextArea.setLineWrap(true);
        sourceTextArea.setRows(2);
        jScrollPane1.setViewportView(sourceTextArea);

        sourceGoButton.setText("Go");
        sourceGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceGoButtonActionPerformed(evt);
            }
        });

        sourceClearButton.setText("Clear");
        sourceClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(sourceGoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sourceClearButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sourceClipboardButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sourceClipboardButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceGoButton)
                    .addComponent(sourceClearButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Source", jPanel2);

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane2.setViewportView(outputTextArea);

        outputResultsLabel.setText("Results:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(outputResultsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(outputResultsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Output", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceClipboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceClipboardButtonActionPerformed
        try {
            // Copy text from clipboard into input box
            sourceTextArea.setText(getClip());
        } catch (Exception ex) {
            Logger.getLogger(TextPatternsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sourceClipboardButtonActionPerformed

    private void sourceClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceClearButtonActionPerformed
        // Clear Button
        sourceTextArea.setText("");
    }//GEN-LAST:event_sourceClearButtonActionPerformed

    private void sourceGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceGoButtonActionPerformed
        // Go button
        getMode();
        compileReg();
        
        
    }//GEN-LAST:event_sourceGoButtonActionPerformed

    private void modeEmailsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeEmailsRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeEmailsRadioActionPerformed

    private void modePhoneRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modePhoneRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modePhoneRadioActionPerformed

    private void modeWebsiteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeWebsiteRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeWebsiteRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextPatternsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextPatternsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextPatternsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextPatternsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextPatternsUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton modeEmailsRadio;
    private javax.swing.ButtonGroup modeOptionsGroup;
    private javax.swing.JRadioButton modePhoneRadio;
    private javax.swing.JRadioButton modeWebsiteRadio;
    private javax.swing.JLabel outputResultsLabel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton sourceClearButton;
    private javax.swing.JButton sourceClipboardButton;
    private javax.swing.JButton sourceGoButton;
    public static javax.swing.JTextArea sourceTextArea;
    // End of variables declaration//GEN-END:variables
    public static String S = "c@c.com and calum@test.com and what@wwwww.com";
    public static Matcher M = Pattern.compile("[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+").matcher(S);

}
